[CLIENT]
; Première ligne utile du tableau client (premier article)
LOWEST_CLIENT_ROW = 4

; Dernière ligne utile des tableaux clients
HIGHEST_CLIENT_ROW = 300


[CENTRAL]
; Première ligne utile du tableau central
LOWEST_CENTRAL_ROW = 2

; Dernière ligne utile du tableau central
HIGHEST_CENTRAL_ROW = 300


[LAYOUT]
; Position du nom du client dans son fichier
CLIENT_NAME_ROW = 1
CLIENT_NAME_COLUMN = 3

; Ligne et première colonne des clients dans le tableau central
CLIENT_ROW = 1
FIRST_CLIENT_COLUMN = 3

[BACKUP]
; Sauvegarde du fichier central :
; none = aucune, once = ecrase la dernière sauvegarde, date = sauvegarde à chaque exécution
BACKUP_TYPE = once

[PATH]
; Répertoire où sont situés les fichiers de travail (tableau central, tableaux clients, etc.)
; Laisser vide pour utiliser le répertoire courant (pas d'espace SVP)
WORKING_DIRECTORY = /home/julien/Musique/

[FILES]
; Fichier modèle pour le tableau central
CENTRAL_WORKBOOK = Commandes.xlsx

; Fichier où sera enregistrée la sortie du programme
OUTPUT_WORKBOOK = Commandes.xlsx

; Repertoire contenant les tableaux clients
CLIENT_PATH = clients

FICHIER_CORRESPONDANCE_CLIENTS = script/Correspondances_clients.csv

